"""Render existing aggregate JSON only; never open models or arrays."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parent;OUT=ROOT/'completion'
r=json.loads((OUT/'ROUND09_RESULTS.json').read_text());arms=('zero_decay','coupled_l2')
ref=r['retained_reference']['metrics'];lines=[]
def add(s=''):lines.append(s)
def table(headers,rows):
    add('| '+' | '.join(headers)+' |');add('| '+' | '.join('---' for _ in headers)+' |')
    for row in rows:add('| '+' | '.join(map(str,row))+' |')
    add()
f=lambda x:f'{x:.6f}'
add('# Round09 — fixed coupled decay fails the promotion gate');add()
add('**Coupled AdamAMSGrad decay 1e-4 lowers selected pooled raw-f R² from .415284 to .361496 in this paired run.** Both are below the retained Round05 original control at .447169. The frozen dual +.003 gate fails; this coefficient and budget establish no improvement or achievement of the .60 target.');add()
add('Both arms completed 60 epochs and 112,860 updates, one original attempt each, no production failure or resume. Every validation uses all 6,686 molecules × ten states = 66,860 printed raw-f labels, including zeros. Earliest minimum pooled validation SSE across epochs 0–60 selects the checkpoint; fixed60 is reported separately. No calibration, averaging, permutation, exclusion or TEST scoring.');add()
add('## Selected and fixed60 results');add()
table(['Policy','Arm','Epoch','R²','f RMSE','f MAE','Energy RMSE (eV)','Energy MAE (eV)'],[
    [p,a,r['arms'][a]['selected_epoch'] if p=='selected_best' else 60,*[f(m['pooled'][k]) for k in ('r2','rmse','mae')],f(m['energy']['rmse']),f(m['energy']['mae'])]
    for p in ('selected_best','fixed60') for a in arms for m in [r['arms'][a][p]]]+
    [['retained selected','Round05 control',45,*[f(ref['pooled'][k]) for k in ('r2','rmse','mae')],f(ref['energy']['rmse']),f(ref['energy']['mae'])]])
g=r['gate'];add(f"Selected coupled_l2 ΔR² is {f(g['candidate_delta_r2_vs_contemporaneous_zero_decay'])} versus its contemporaneous control and {f(g['candidate_delta_r2_vs_retained_reference'])} versus retained. Each required at least +.003. No extension, seed allocation, coefficient sweep or optimizer replacement is authorized by this result.");add()
add('## All states');add()
for p in ('selected_best','fixed60'):
    add('### '+p);add();add('Each state includes 6,686 labels. Cells show R² / RMSE / MAE.');add()
    table(['State',*arms],[[f'S{k}',*[f"{f(r['arms'][a][p]['per_state'][str(k)]['r2'])} / {f(r['arms'][a][p]['per_state'][str(k)]['rmse'])} / {f(r['arms'][a][p]['per_state'][str(k)]['mae'])}" for a in arms]] for k in range(1,11)])
    improved=[f'S{k}' for k in range(1,11) if r['arms']['coupled_l2'][p]['per_state'][str(k)]['sse']<r['arms']['zero_decay'][p]['per_state'][str(k)]['sse']]
    add('Coupled decay has lower state SSE than zero decay on '+(', '.join(improved) if improved else 'no states')+'. All states remain included.');add()
add('## Bright tails, false bright predictions and concentrated error');add()
add('Fixed TRAIN target thresholds q90=.0549 and q99=.2406 define the tails. These subgroups never alter pooled scores.');add()
table(['Policy','Arm','Tail','Count','RMSE','MAE','SSE'],[[p,a,q,m['count'],f(m['rmse']),f(m['mae']),f(m['sse'])] for p in ('selected_best','fixed60') for a in arms for q in ('q90','q99') for m in [r['arms'][a][p]['bright_tail'][q]]])
keys=('true_0_pred_0','true_0_pred_1','true_1_pred_0','true_1_pred_1')
add('The four q99 bins sum to all 66,860 labels and the full SSE. Cells show count / SSE. Bin membership depends on model predictions, so changes are descriptive decompositions, not causal effects on fixed subgroups.');add()
table(['Policy','Arm','T0/P0','T0/P1 false bright','T1/P0 missed bright','T1/P1'],[[p,a,*[f"{b[k]['count']} / {f(b[k]['sse'])}" for k in keys]] for p in ('selected_best','fixed60') for a in arms for b in [r['arms'][a][p]['false_bright_bins']]])
c=r['arms']['coupled_l2']['selected_best'];z=r['arms']['zero_decay']['selected_best']
for title,x,y in [('selected zero_decay',c,z),('retained Round05',c,ref)]:
    add(f"Coupled decay versus {title}: Δ pooled MAE {f(x['pooled']['mae']-y['pooled']['mae'])}; Δ energy RMSE {f(x['energy']['rmse']-y['energy']['rmse'])} eV; Δ energy MAE {f(x['energy']['mae']-y['energy']['mae'])} eV; Δ true-q90 RMSE {f(x['bright_tail']['q90']['rmse']-y['bright_tail']['q90']['rmse'])}; Δ true-q99 RMSE {f(x['bright_tail']['q99']['rmse']-y['bright_tail']['q99']['rmse'])}; Δ false-bright SSE {f(x['false_bright_bins']['true_0_pred_1']['sse']-y['false_bright_bins']['true_0_pred_1']['sse'])}. Positive error differences are worse.")
add();table(['Policy','Arm','Top1% count','Top1% SSE share','Prediction q99','Prediction max','Error q99','Error max'],[[p,a,e['top_error_count'],f(e['top_error_sse_share']),f(e['prediction_quantiles']['0.99']),f(e['prediction_quantiles']['1.0']),f(e['absolute_error_quantiles']['0.99']),f(e['absolute_error_quantiles']['1.0'])] for p in ('selected_best','fixed60') for a in arms for e in [r['arms'][a][p]['error_distribution']]])
add('Full SSE, MAE, counts and additional quantiles are in ROUND09_RESULTS.json. No error outlier was removed.');add()
add('## Trajectories and optimizer diagnostics');add()
add('TRAIN metrics are weighted pre-update minibatch trajectory aggregates, not fixed-checkpoint TRAIN evaluations. Validation is evaluated at each completed checkpoint. Both arms optimize original LE+Ls; reported raw-f MSE and decorrelation remain diagnostics. A difference between these TRAIN and validation summaries is not an exactly matched generalization-gap estimate.');add()
table(['Arm/epoch','TRAIN f MSE','TRAIN LE','TRAIN Ls','VAL LE','VAL Ls','Clip fraction'],[[f'{a}/{ep}',f(t['train']['raw_f_mse']),f(t['train']['energy']),f(t['train']['trace']),f(t['validation']['base_objective']['energy']),f(t['validation']['base_objective']['trace']),f(t['gradient_clip_fraction'])] for a in arms for ep,t in r['arms'][a]['trajectory_snapshots'].items()])
table(['Arm/epoch','Parameter norm','Coupled-term norm','Decay/task ratio','Effective gradient norm','Min |radial beta|','Offset min/max'],[[f'{a}/{ep}',f(d['trainable_parameter_l2']),f(d['coupled_term_l2']),f(d['regularized_decay_task_ratio']),f(d['effective_gradient_l2']),f(d['radial_beta_min_abs']),f"{f(d['energy_offset_min'])} / {f(d['energy_offset_max'])}"] for a in arms for ep,t in r['arms'][a]['trajectory_snapshots'].items() for d in [t['regularization_diagnostics']]])
table(['Arm','Checkpoint','Parameter norm','Min |radial beta|','Offset min/max'],[[a,p,f(v['trainable_parameter_l2']),f(v['radial_beta_min_abs']),f"{f(v['energy_offset_min'])} / {f(v['energy_offset_max'])}"] for a in arms for p,v in r['arms'][a]['checkpoint_parameter_aggregates'].items()])
add('Task gradients are clipped at5 before Adam adds lambda*p internally and before first/second/AMSGrad-max moment updates. This is coupled L2, not AdamW; the effective gradient is not clipped a second time. Detached norms use the same grad!=None subset; ratio denominator is max(task norm,1e-12), with zero/below-floor counts preserved. Means are molecule weighted, radial beta is an epoch minimum, offset extrema are recorded extrema. Effective-gradient norm is not the adaptive update norm.');add()
add('Every recorded epoch has135 live-gradient parameters and no grad=None parameters. Dormant right-F tensors remain unchanged across selected/final checkpoints; both transport theta tensors remain exactly zero. Radial and offset summaries document the broad all-parameter decay treatment; they do not identify why errors changed. No nonfinite failure, missing optimizer state or resource interruption was observed, and no coefficient or parameter exclusion was adjusted.');add()
add('## Conditional uncertainty and repeated-control limits');add()
u=r['paired_uncertainty'];add(f"The paired bootstrap resamples {u['component_groups']} validation identity groups from the fixed6,686-molecule cohort, retaining all molecules and ten states together within each sampled group. Draw molecule counts vary. Seed{u['seed']}, {u['draws']} draws, recomputed pooled SST. These descriptive intervals are conditional on the chosen checkpoints and reused validation; they do not capture checkpoint-selection or training-seed uncertainty. The retained aggregate has no paired interval.");add()
table(['Policy','Contrast','Delta R²','Descriptive95% interval'],[[p,name,f(v['delta_r2']),f"[{f(v['descriptive_percentile_interval'][0])}, {f(v['descriptive_percentile_interval'][1])}]"] for p in ('selected_best','fixed60') for name,v in u['comparisons'][p].items()])
add('Declared original controls previously selected .447169 (Round05), .404798 (Round06), .409104 (Round07), .417636 (Round08), and .415284 here. Common initial tensors/order/settings do not guarantee identical CUDA trajectories; wrappers, diagnostics and workloads across rounds differ. No source of that variation was isolated. This matched pair is evidence against the specified coefficient/parameter treatment at this budget, not proof that regularization in general fails or that a particular physical or generalization mechanism caused the result.');add()
add('## Fixed recipe and artifacts');add()
add('Original PSD MTO16/query32/router128/head128, core128/three blocks, fresh seed/order11 and newTRAIN-only statistics. Original LE+Ls, AdamAMSGrad LR.001/betas(.9,.999)/eps1e-8/batch64/clip5, FP32/noAMP/noTF32/two threads, fixed60 without scheduler/early stopping. One ordered135-tensor group contains1,552,092 values, including biases, normalization, embeddings, offsets and trainable radial parameters. Exactly11 dormant right-F/transport tensors and all buffers are excluded. foreach/fused remainNone; grad=None would skip decay/state, whereas a zero gradient receives decay. Only weight_decay differs:0 versus1e-4. The five toy steps and six discarded technical TRAIN updates never initialize production.');add()
add('Native f = 2 E_eV trace(A) / (3 × 27.211386245988), evaluated in FP64 against printed raw-f targets. Predicted energy uses unchanged softplus and A is PSD; no teacher energy or output repair. Geometry-only exports embed config, TRAIN statistics, original mode/contract and one full model. Forward inputs are (z,pos,batch,n,edge_index).');add()
table(['Arm','Selected epoch','Server standalone checkpoint','SHA256'],[[a,r['arms'][a]['selected_epoch'],r['verification'][a]['checkpoint_paths']['geometry_best.pt'],r['verification'][a]['checkpoint_hashes']['geometry_best.pt']] for a in arms])
table(['Arm','Measured train+validation hours'],[[a,f(r['arms'][a]['wall_training_validation_seconds']/3600)] for a in arms])
add('The retained v2 reference is still Round05 original control45: `/home/inspur/MTO-1/research/single_model_20260929/round05_scratch_preparation/runs/control/geometry_best.pt`, SHA `e71c63da8bb3b8214e014ca64946fecab97fbc210cb068c0b1a3eefa3bbf8f1e`, R² .44716940136585204. Use its matching Round05 loader. It remains below .60, without current TEST or independent-seed confirmation.');add()
add('All360 source pins, authority/review/publication,60 orders,61 history rows,112860 updates, earliest selection,135 optimizer members/options/moments/steps/RNG, access ledgers and checkpoint hashes passed. Standalone tensors equal selected checkpoint tensors; mode/contract/provenance match. Stored buffer fingerprint format is valid; strict buffer reconstruction/export parity was a preparation check, not a new terminal forward. Process absence is exit evidence, not an observed child OS exit code.');add()
add('This analysis reads four saved validation output sets, CPU checkpoint contents, validation component metadata and the published retained aggregate. It creates no model and opens no raw dataset targets or TEST arrays. Every saved truth/mask agrees. Weights, optimizer tensors, raw/private identity and prediction arrays stay server-only; lightweight manifests never expand opaque input hashes into payloads. Exact commands and recovery/completed-stage refusal are in ROUND09_REPRODUCE.md.');add()
add('The v2 partition is disjoint under audited conservative identity rules, not absolute chemical-identity proof or external fresh data. Its sealed TEST contains5,989 oldTRAIN,361 oldvalidation and336 oldTEST rows. Historical exposure, reused validation, one initialization and control variability limit conclusions. The initial technical GPU1 admission rejection occurred before a scientific child/update; its snapshot and successful separate GPU4 six-update retry remain preserved. Production onGPU1/2 completed without retry.');add()
add('![Validation and TRAIN trajectories](ALIGNED_VALIDATION_AND_TRAIN_CURVES.svg)');add()
add('![Regularization diagnostics](REGULARIZATION_TRAJECTORIES.svg)');add()
add('## Decision boundary');add()
add('The fixed coupled-decay contrast fails its promotion gate. Retain the Round05 reference and preserve this negative result; no coefficient sweep, new group exclusions, AdamW substitution, extension, seeds, TEST release or next numerical pilot follows automatically. Root owns closeout and D-first publication.');add()
p=OUT/'ROUND09_REPORT.md';assert not p.exists(),'Completed report must not be overwritten'
p.write_text('\n'.join(lines)+'\n')
print(json.dumps({'report_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'script_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}))
